pool:
  name: Azure Pipelines
  demands: npm
  timeoutInMinutes: 10
  vmImage: 'windows-latest'

# Build package whenever we push to master or release branch.
trigger:
  batch: true
  branches:
    include:
      - master
      - main
      - release/*

variables:
  workingDir: $(Build.SourcesDirectory)

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    displayName: 'Use Node 16.14.x'
    inputs:
      versionSpec: 16.14.x

  - task: Npm@1
    displayName: 'Install yarn'
    inputs:
      command: custom
      verbose: false
      customCommand: 'npm install -g yarn'

  - task: Npm@1
    displayName: 'Build package in production mode'
    inputs:
      command: custom
      verbose: false
      customCommand: 'yarn build-prod'

  - task: Npm@0
    displayName: 'Pack library'
    inputs:
      command: install

  - task: PowerShell@2
    displayName: 'Stringpoke curent maj/min version from package.json'
    inputs:
      targetType: 'inline'
      workingDirectory: $(workingDir)
      script: |
        $majMin = ((Get-Content .\package.json | ConvertFrom-Json).version) -replace ".{1}$"
        $buildNumberParts = "$(Build.BuildNumber)".Split(".")
        $buildNumber = $buildNumberParts[0]
        If ($buildNumberParts[1] -as [int] -lt 10)
        {
          $buildNumber += "0"
        }
        $buildNumber += $buildNumberParts[1]
        Write-Host "Parsed major minor version: '$($majMin)$($buildNumber)'"
        Write-Host "##vso[task.setVariable variable=version]$($majMin)$($buildNumber)"
  - task: Npm@1
    displayName: 'npm version'
    inputs:
      command: custom
      workingDir: $(workingDir)
      verbose: false
      customCommand: 'version $(version) --force --no-git-tag-version'

  - task: Npm@1
    displayName: 'npm publish'
    inputs:
      command: 'publish'
      verbose: false
      publishRegistry: 'useFeed'
      publishFeed: 't1rearc-base-ui-feed'
